name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print runner info
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner name: ${{ runner.name }}"
          echo "Runner temp directory: ${{ runner.temp }}"

      - name: List files
        run: ls -la

      - name: Test Python (optional)
        run: python3 --version

